# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monitoring.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'monitoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10monitoring.proto\x12\nmonitoring\"\x7f\n\x0c\x43lientStream\x12/\n\x0cmonitor_data\x18\x01 \x01(\x0b\x32\x17.monitoring.MonitorDataH\x00\x12\x33\n\x0e\x63ommand_result\x18\x02 \x01(\x0b\x32\x19.monitoring.CommandResultH\x00\x42\t\n\x07\x63ontent\"L\n\x0bMonitorData\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x0e\n\x06metric\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\"\x8f\x01\n\x0e\x43ommandRequest\x12<\n\x0c\x63ommand_type\x18\x01 \x01(\x0e\x32&.monitoring.CommandRequest.CommandType\x12\x11\n\tparameter\x18\x02 \x01(\t\",\n\x0b\x43ommandType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x10\n\x0cSET_INTERVAL\x10\x01\"x\n\rCommandResult\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x34\n\x10original_command\x18\x02 \x01(\x0b\x32\x1a.monitoring.CommandRequest\x12\x0e\n\x06output\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x04 \x01(\x08\x32P\n\x07Monitor\x12\x45\n\x07monitor\x12\x18.monitoring.ClientStream\x1a\x1a.monitoring.CommandRequest\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTSTREAM']._serialized_start=32
  _globals['_CLIENTSTREAM']._serialized_end=159
  _globals['_MONITORDATA']._serialized_start=161
  _globals['_MONITORDATA']._serialized_end=237
  _globals['_COMMANDREQUEST']._serialized_start=240
  _globals['_COMMANDREQUEST']._serialized_end=383
  _globals['_COMMANDREQUEST_COMMANDTYPE']._serialized_start=339
  _globals['_COMMANDREQUEST_COMMANDTYPE']._serialized_end=383
  _globals['_COMMANDRESULT']._serialized_start=385
  _globals['_COMMANDRESULT']._serialized_end=505
  _globals['_MONITOR']._serialized_start=507
  _globals['_MONITOR']._serialized_end=587
# @@protoc_insertion_point(module_scope)
